version: '3.4'
services:
    mariadb:
        # MariaDB version to use
        image: mariadb:10.3.7
        # Environmental variables set for the image, easily changeable
        environment:
            MYSQL_ROOT_PASSWORD: password
            MYSQL_DATABASE: medici
            MYSQL_USER: user
            MYSQL_PASSWORD: password
        # Mount the SQL directory from the local host directory to Docker entrypoint, for automatic .sql file execution
        volumes: 
            - ${PWD}/sql/:/docker-entrypoint-initdb.d
        # Ease of use (not strictly necessary, but allows for connecting to MySQL directly from host machine to localhost:3306
        ports:
            - "3306:3306"
    php:
        # Specify the directory context with the Dockerfile
        build: server
        # Mount the PHP server code into the /var/www/html Apache server directory on the Docker container
        volumes:
            - ${PWD}/src/:/var/www/html
        # Expose the port 8081 on the local machine for ease of use in testing
        ports:
            - "8081:80"
    nginx:
        # Nginx version (arbitrarily chosen)
        image: nginx:1.15.0
        # Mount the AngulaarJS client code (not fully tested yet)
        volumes:
            - ${PWD}/client/:/var/www/html
        # Expose the port 8080 on the local machine
        ports:
            - "8080:80"
