version: '3.4'
services:
    mariadb:
        # MariaDB version to use
        image: mariadb:10.3.7
        # Environmental variables set for the image, easily changeable
        environment:
            MYSQL_ROOT_PASSWORD: password
            MYSQL_DATABASE: medici
            MYSQL_USER: user
            MYSQL_PASSWORD: password
        # Mount the SQL directory from the local host directory to Docker entrypoint, for automatic .sql file execution
        volumes: 
            - ${PWD}/sql/:/docker-entrypoint-initdb.d
        # Ease of use (not strictly necessary, but allows for connecting to MySQL directly from host machine to localhost:3306
        ports:
            - "3306:3306"
    php:
        # Specify the directory context with the Dockerfile
        build: 
            context: ./server
            dockerfile: Dockerfile
        # Mount the PHP server code into the /var/www/html Apache server directory on the Docker container
        volumes:
           - ${PWD}/server/src/:/var/www/html
        environment:
            - "DB_PORT=3306"
            - "DB_HOST=localhost"
            - "DB_DATABASE=medici"
            - "DB_USERNAME=root"
            - "DB_PASSWORD=password"
        # Expose the port 8000 on the local machine for ease of use in testing
        ports:
            - "8000:8000"
